{{- with .Values.telemetry }}
{{- if eq (.enabled | toString) "true" }}
---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default "5" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    {{- if .additionalAnnotations }}
    {{- include "tpl.additionalAnnotations" .additionalAnnotations | nindent 4 }}
    {{- end }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- if .additionalLabels }}
    {{- include "tpl.additionalLabels" .additionalLabels | nindent 4 }}
    {{- end }}
spec:
  tracing:
    {{- range .tracing }}
    - providers:
        {{- range .providers }}
        - name: {{ .name }}
        {{- end }}
      {{- if hasKey . "randomSamplingPercentage" }}
      randomSamplingPercentage: {{ .randomSamplingPercentage }}
      {{- end }}
      {{- if hasKey . "disableSpanReporting" }}
      disableSpanReporting: {{ .disableSpanReporting }}
      {{- end }}
    {{- end }}
{{- end }}
{{- end }}
