apiVersion: v2
name: setup-kiali
description: Installs the Kiali operator (kiali-ossm) and a Kiali instance integrated with OpenShift platform monitoring (thanos-querier), including ServiceMonitor/PodMonitor resources for istiod and Envoy proxies.
type: application
version: 1.0.0
home: https://github.com/mcapala/helm-charts/tree/main/charts/setup-kiali
maintainers:
  - name: mcapala
dependencies:
  - name: tpl
    version: ~1.0.0
    repository: https://charts.stderr.at/
  - name: helper-operator
    version: ~1.0.0
    repository: https://charts.stderr.at/
  - name: helper-status-checker
    version: ~4.0.0
    repository: https://charts.stderr.at/
    condition: helper-status-checker.enabled
sources:
  - https://github.com/mcapala/helm-charts
keywords:
  - kiali
  - servicemesh
  - observability
